package com.tweetcrawl.ontology;

import jade.content.Predicate;

public class FileTwitter implements Predicate {

	private String name;

	/**
	 * Allows to get the name of the file generated by the tweetCrawler
	 *
	 * @return name of the file
	 */
	public String getName() {
		return name;
	}

	/**
	 * Allows to modify the name of the file containing resulting tweets
	 *
	 * @param name the new file name
	 */
	public void setName(String name) {
		this.name = name;
	}
}
